import type { IncomingMessage, ServerResponse } from "node:http";
import type { ApiContext } from "./api-context.js";
import { parseBody, sendJson } from "./route-utils.js";

export async function handleMobileChatRoutes(
    req: IncomingMessage,
    res: ServerResponse,
    url: URL,
    pathname: string,
    ctx: ApiContext
): Promise<boolean> {
    if (!pathname.startsWith("/api/mobile/")) {
        return false; // Not handled here
    }

    // W16-A1: Generate Pairing Code
    if (pathname === "/api/mobile/pairing-code/generate" && req.method === "POST") {
        if (!ctx.mobileManager) {
            sendJson(res, 500, { error: "Mobile Manager not initialized" });
            return true;
        }

        try {
            const codeData = await ctx.mobileManager.requestPairingCode();
            sendJson(res, 200, codeData);
        } catch (err: any) {
            sendJson(res, 500, { error: err.message || "Failed to generate pairing code" });
        }
        return true;
    }

    // W16-A1: Get Pairing Status
    if (pathname === "/api/mobile/status" && req.method === "GET") {
        if (!ctx.mobileManager) {
            sendJson(res, 500, { error: "Mobile Manager not initialized" });
            return true;
        }

        const activeCode = ctx.mobileManager.getActiveCode();
        let activePairing = ctx.mobileManager.getActivePairing();

        // If a code generated by Desktop is awaiting mobile pairing, wait for the Control Plane
        if (activeCode && !activePairing) {
            // We fire this asynchronously so it doesn't block the UI's status query
            ctx.mobileManager.waitForControlPlaneToken(activeCode.code).then((status) => {
                if (status && status.paired && status.accessToken && status.relayUrl) {
                    // The mobile app successfully claimed the OTP and got a token. 
                    // Save it locally!
                    let newPairing = ctx.storage.mobilePairings.setPairing({
                        deviceId: status.desktopDeviceId || ctx.mobileManager!.getDesktopDeviceId(),
                        accessToken: status.accessToken,
                        relayUrl: status.relayUrl
                    });

                    // Clear the active code since it was consumed
                    ctx.mobileManager!.clearActiveCode();

                    // Start the Gateway plugin sync engine
                    const rpcClient = ctx.getRpcClient?.();
                    if (rpcClient?.isConnected()) {
                        rpcClient.request("mobile_chat_start_sync", {
                            accessToken: status.accessToken,
                            relayUrl: status.relayUrl,
                            desktopDeviceId: newPairing.deviceId
                        }).catch((err: any) => {
                            console.error("Failed to start mobile sync via RPC:", err);
                        });
                    }
                }
            }).catch(e => console.error("Pairing wait failed", e));
        }

        sendJson(res, 200, {
            pairing: activePairing || null,
            activeCode: activeCode || null,
            desktopDeviceId: ctx.mobileManager.getDesktopDeviceId(),
        });
        return true;
    }

    // W16-A1: Disconnect Pairing
    if (pathname === "/api/mobile/disconnect" && req.method === "DELETE") {
        if (!ctx.mobileManager) {
            sendJson(res, 500, { error: "Mobile Manager not initialized" });
            return true;
        }

        try {
            ctx.mobileManager.disconnectPairing();

            // Stop the Gateway plugin sync engine
            const rpcClient = ctx.getRpcClient?.();
            if (rpcClient?.isConnected()) {
                rpcClient.request("mobile_chat_stop_sync", {}).catch((err: any) => {
                    console.error("Failed to stop mobile sync via RPC:", err);
                });
            }

            sendJson(res, 200, { success: true });
        } catch (err: any) {
            sendJson(res, 500, { error: err.message || "Failed to disconnect mobile pairing" });
        }
        return true;
    }

    return false;
}
